### ISSUE TITLE
Keine Anzeige von SOC, SOH und keine Button

### ISSUE THREAD

**Issue by miriammichael** [flobz/psa_car_controller#1232]
Hallo 
Leider sieht mein Control Tab so aus:
![image](https://github.com/user-attachments/assets/1ac72881-344c-4439-b0ea-d776472c3e26)
In der vorherigen Version waren auch keine Buttons aber zumindest die Akku Anzeigen

Installation im Docker
Danke

**Comment by RasputinBerry** [comment]
... ich bin zurück auf v3.5.7 ... jetzt sind wenigstens wieder der SoC, SoH und Milage zu sehen, der Rest fehlt (natürlich) immer noch.

**Comment by miriammichael** [comment]
Danke das werde ich auch mal probieren

**Comment by TorbjornMohn** [comment]
Same problem for me. ALso version 3.7.3 no longer gets Trip and Charger information updatet. Reads only data already in the local HA database prior to the upgrade.

**Comment by Tilde81** [comment]
same issue here from me (control website stays blank, just a link to e208 is present)

logfile
2026-06-18 21:54:56,580 :: ERROR :: get_control_tabs:

Traceback (most recent call last):

File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py", line 58, in get_control_tabs

preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'status'

**Comment by Tilde81** [comment]
some info for the developper probably indicating a bug?

2026-06-18 22:15:15,357 :: ERROR :: Can't get_price of charge: 2026-06-17 20:02:32+00:00-2026-06-17 16:25:37+00:00 prices: []

Traceback (most recent call last):

File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/config_repository.py", line 140, in _get_ac_charge_price

res = round(consumption * mean(prices) / self.charger_efficiency, 2)

^^^^^^^^^^^^

thx for your work

**Comment by Trebila** [comment]
still the same with v3.7.4, no panel on control window:

<img width="1576" height="410" alt="Image" src="https://github.com/user-attachments/assets/c00a79d0-f96d-41d5-922d-c352885f8d64" />

<img width="1594" height="354" alt="Image" src="https://github.com/user-attachments/assets/f430549e-2544-4a76-aaf3-fd2245bff3c5" />

**Comment by HenningS81** [comment]
Bei mir das selbe.

**Comment by TorbjornMohn** [comment]
No change with 3.7.4 here either. Still same problem

**Comment by 647ncypfkf-star** [comment]
Same problem - with 3.7.4

**Comment by Arnoudd** [comment]
Same issue here with v3.7.4. I also reverted to v3.5.7 to get it working again.

**Comment by cosmo35037** [comment]
Same issue with 3.7.4

**Comment by Pilotmaverick** [comment]
Seems to be the same with 3.7.5...

**Comment by RasputinBerry** [comment]
Hi @flobz, why doesn't it work (also #1185)? 
It would be nice if you could give an explanation. 

Thank you for your work

**Comment by TorbjornMohn** [comment]
Same problem with v3.7.5. Why is it so difficult to fix? Apparently it works with v3.5.7.

**Comment by Haro3** [comment]
Bei mir funktionert 3.57 auch nicht.

**Comment by mk-devs** [comment]
Same on Corsa-e 2021

2026-07-20 07:49:40,110 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py", line 59, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status'

**Comment by TorbjornMohn** [comment]
Before I give up on this addon, noone seems to care. There is no solution to this known issue? Does anyone know of an alternative addon that works for Peugeot EVs??

**Comment by cosmo35037** [comment]
Same problem with v3.7.6, which is rendering this app completely useless, unfortunately.

**Comment by RasputinBerry** [comment]
... Version 3.5.7 was working until a few days ago (SoC, SoH, and mileage), but now even that version has stopped updating.

I assume Stellantis is behind this and the developer can no longer access the data (EU Data Act).
European car manufacturers (or all of them?) just want to monetize **our data**. 
Let's see how long this lasts ... (I'll be selling my Corsa soon...).

Still, though: a statement from the developer would be nice — thanks for the work done so far!!!

**Comment by Dirtylife** [comment]
I had the same problem with v3.7.5 (runs on a Raspberry Pi 5B with Debian 13).

After a long search, I have been able to narrow the cause in the control.pyp. (for me: /usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py)

### The following patch helped me:
**Original file of v3.7.5 (see line 79 / 80 - the last two lines):**
`        tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el]))
    return dbc.Tabs(id="control-tabs", children=tabs)`

**My Patch:**
`            tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, tab_id="tab-" + car.vin,
                            children=[dbc.Row(buttons_row), *el]))
    return dbc.Tabs(id="control-tabs", active_tab="tab-" + config.myp.vehicles_list[0].vin, children=tabs)`

### Howto:

1. Make a Backup :-)
2. Stop psa-car-controller
3. Patch
4. Start psa-car-controller

**USE IT WITH CARE - I´AM NOT A PRO.**

**Comment by TorbjornMohn** [comment]
> I had the same problem with v3.7.5 (runs on a Raspberry Pi 5B with Debian 13).
> 
> After a long search, I have been able to narrow the cause in the control.pyp. (for me: /usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py)
> 
> ### The following patch helped me:
> **Original file of v3.7.5 (see line 79 / 80 - the last two lines):** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", children=tabs)`
> 
> **My Patch:** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, tab_id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", active_tab="tab-" + config.myp.vehicles_list[0].vin, children=tabs)`
> 
> ### Howto:
> 1. Make a Backup :-)
> 2. Stop psa-car-controller
> 3. Patch
> 4. Start psa-car-controller
> 
> **USE IT WITH CARE - I´AM NOT A PRO.**

I wish I knew where to find that file in my Home Assistant installation. Would be nice though to have it fixed by the developers :-)

**Comment by RasputinBerry** [comment]
Same request from me: Docker in QNAP NAS ...

**Comment by Dirtylife** [comment]
> > I had the same problem with v3.7.5 (runs on a Raspberry Pi 5B with Debian 13).
> > After a long search, I have been able to narrow the cause in the control.pyp. (for me: /usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py)
> > ### The following patch helped me:
> > **Original file of v3.7.5 (see line 79 / 80 - the last two lines):** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", children=tabs)`
> > **My Patch:** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, tab_id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", active_tab="tab-" + config.myp.vehicles_list[0].vin, children=tabs)`
> > ### Howto:
> > 
> > 1. Make a Backup :-)
> > 2. Stop psa-car-controller
> > 3. Patch
> > 4. Start psa-car-controller
> > 
> > **USE IT WITH CARE - I´AM NOT A PRO.**
> 
> I wish I knew where to find that file in my Home Assistant installation. Would be nice though to have it fixed by the developers :-)

I don´t use Containers.

=> I recommend using an AI for the guided modification of "control.py".

Something like this:
Schritt 1: Container-ID finden
`docker ps`

Schritt 2: Container betreten
`docker exec -it <container_id_oder_name> /bin/bash`

Schritt 3: Datei control.py suchen
`find / -name "control.py" 2>/dev/null`

Schritt 4: Datei bearbeiten
`nano /pfad/zur/control.py`

Schritt 5: Container verlassen
`exit`

Schritt 5: Container neu starten
`docker restart <container_id_oder_name>`

**Comment by 647ncypfkf-star** [comment]
Still the same problem with v3.7.6 😒

**Comment by Arnoudd** [comment]
> I had the same problem with v3.7.5 (runs on a Raspberry Pi 5B with Debian 13).
> 
> After a long search, I have been able to narrow the cause in the control.pyp. (for me: /usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/control.py)
> 
> ### The following patch helped me:
> **Original file of v3.7.5 (see line 79 / 80 - the last two lines):** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", children=tabs)`
> 
> **My Patch:** ` tabs.append(dbc.Tab(label=label, id="tab-" + car.vin, tab_id="tab-" + car.vin, children=[dbc.Row(buttons_row), *el])) return dbc.Tabs(id="control-tabs", active_tab="tab-" + config.myp.vehicles_list[0].vin, children=tabs)`
> 
> ### Howto:
> 1. Make a Backup :-)
> 2. Stop psa-car-controller
> 3. Patch
> 4. Start psa-car-controller
> 
> **USE IT WITH CARE - I´AM NOT A PRO.**

Thanks! This worked for me. On the latest version this fixed it.

I made an pull request. Hopefully this will fix it for everyone else.
https://github.com/flobz/psa_car_controller/pull/1269

**Comment by MarkusLab12** [comment]
...i did something similar as a hot-fix:
https://github.com/flobz/psa_car_controller/issues/1266#issuecomment-5266916839

**Comment by RasputinBerry** [comment]
@flobz: v3.7.7 works fine for the contol-button, Thank you.

But what about #1185 ? 

<img width="1126" height="562" alt="Image" src="https://github.com/user-attachments/assets/c36dba06-abd7-4a6d-a76f-741037dd8c44" />
